# Generated by Django 4.2 on 2023-04-12 15:35

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория ')),
                ('name_slug', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('description_short', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание краткое')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание полное')),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Категория ',
                'verbose_name_plural': '2. Категории',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название региона')),
                ('name_slug', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('description_short', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание краткое')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание полное')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': '1. Регионы',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название города')),
                ('name_slug', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('image_full', models.ImageField(blank=True, null=True, upload_to='data/city/full', verbose_name='Большое изображение')),
                ('image_thumb', models.ImageField(blank=True, null=True, upload_to='data/city/thumb', verbose_name='Маленькое изображение')),
                ('description_short', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание краткое')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание полное')),
                ('views', models.IntegerField(default=0)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='data.region')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='CategoryProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_slug', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='data.category')),
            ],
            options={
                'verbose_name': 'Набор свойств',
                'verbose_name_plural': 'Набор свойств категормм',
            },
        ),
    ]
