# Generated by Django 4.2 on 2023-04-12 16:06

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название проекта')),
                ('name_slug', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('image_full', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Большое изображение')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Стартовал')),
                ('end_date', models.DateTimeField(verbose_name='Завершился')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('ready_percent', models.IntegerField(default=0, verbose_name='Процент готовности')),
                ('total_hours', models.IntegerField(default=0, verbose_name='Затрачено часов')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': '1. Проекты',
            },
        ),
        migrations.RemoveField(
            model_name='categoryproperty',
            name='category',
        ),
        migrations.RemoveField(
            model_name='city',
            name='region',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryProperty',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
