# Generated by Django 4.2 on 2023-04-13 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_project_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='sintez',
            name='status',
            field=models.BooleanField(default=None, null=True, verbose_name='Статус'),
        ),
    ]
