# Generated by Django 4.2 on 2023-04-15 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_project_uuid_alter_sintez_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sintez',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sintezes', to='data.project'),
        ),
        migrations.CreateModel(
            name='SintezCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1)),
                ('is_first_card', models.BooleanField(verbose_name='Главный реактив')),
                ('is_final_card', models.BooleanField(verbose_name='Продукт')),
                ('formula_raw', models.CharField(blank=True, max_length=255, null=True, verbose_name='Формула')),
                ('formula_calculated', models.CharField(blank=True, max_length=255, null=True, verbose_name='Формула HTML')),
                ('formula_weight', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Молекулярная масса')),
                ('equavalent', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Эквивалент')),
                ('sample_weight', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Масса образца')),
                ('mmols', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Количество молей')),
                ('sintez', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='data.sintez')),
            ],
            options={
                'verbose_name': 'Карточка синтеза ',
                'verbose_name_plural': 'Карточка синтеза',
                'ordering': ('is_first_card', 'order_num'),
            },
        ),
    ]
