# Generated by Django 4.2 on 2023-04-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_sintez_project_sintezcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='sintez',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='sintez',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Потрачено часов'),
        ),
        migrations.AlterField(
            model_name='sintez',
            name='end_date',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='sintez',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проведения'),
        ),
    ]
