# Generated by Django 4.2 on 2023-04-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_sintez_created_at_sintez_hours_alter_sintez_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sintezcard',
            options={'ordering': ('-is_first_card', 'order_num', 'is_final_card'), 'verbose_name': 'Карточка синтеза ', 'verbose_name_plural': 'Карточка синтеза'},
        ),
        migrations.AlterField(
            model_name='sintez',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код'),
        ),
    ]
