# Generated by Django 4.2 on 2023-04-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_sintezcard_options_alter_sintez_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sintezcard',
            name='is_final_card',
            field=models.BooleanField(blank=True, null=True, verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='sintezcard',
            name='is_first_card',
            field=models.BooleanField(blank=True, null=True, verbose_name='Главный реактив'),
        ),
    ]
