# Generated by Django 4.2 on 2023-04-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_sintezcard_is_final_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sintezcard',
            name='equavalent',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True, verbose_name='Эквивалент'),
        ),
        migrations.AlterField(
            model_name='sintezcard',
            name='formula_weight',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True, verbose_name='Молекулярная масса'),
        ),
        migrations.AlterField(
            model_name='sintezcard',
            name='mmols',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True, verbose_name='Количество молей'),
        ),
        migrations.AlterField(
            model_name='sintezcard',
            name='sample_weight',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True, verbose_name='Масса образца'),
        ),
    ]
