# Generated by Django 4.2 on 2023-04-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_sintezcard_equavalent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True, verbose_name='Потрачено часов'),
        ),
    ]
