# Generated by Django 4.2 on 2023-04-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_project_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Завершился'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Стартовал'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_date',
            field=models.DateField(blank=True, null=True, verbose_name='Обновлен'),
        ),
    ]
