# Generated by Django 4.2 on 2023-04-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_alter_project_end_date_alter_project_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ready_percent',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Процент готовности'),
        ),
    ]
